# Generated by Django 4.0.1 on 2022-03-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('hp', models.IntegerField(default='0')),
                ('attack', models.IntegerField(default='0')),
                ('defense', models.IntegerField(default='0')),
                ('type', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
