# Generated by Django 4.0.1 on 2022-03-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_pokemon_userownedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='userOwnedBy',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='userOwnedBy_id',
            field=models.IntegerField(default=-1),
        ),
    ]
