# Generated by Django 4.0.1 on 2022-03-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_pokemon_userownedby_pokemon_userownedby_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='userOwnedBy_id',
        ),
    ]
